### PR TITLE
Bump jackson-databind to 2.13.0

### PR DESCRIPTION
**Pull request by jpenilla**
Fixes issues when running alongside other gradle plugins using a newer version

### CODE REVIEW

**Comment by modmuss50** [comment]
What kind of issues are you seeing? If other plugins depend on a newer version that should be pulled in. Also curious to know incase I see anyone having issues.

**Comment by jpenilla** [comment]
> If other plugins depend on a newer version that should be pulled in

This is my understanding as well, but it seems like there is some weirdness that can happen with subprojects applying different plugins.

In my case, I apply loom as a settings plugin, in order to use `repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)`, which means even though plugins I apply to some subprojects depend on jackson 2.13.0, I end up with multiple versions on the classpath (the older one I found to be from loom after a build scan).

**Comment by modmuss50** [comment]
This isnt really ideal, as going by that theory doing this will break other plugins that use this older version.

**Comment by jpenilla** [comment]
I agree that it's not ideal, although I still think it's better to break by being more up to date than by being out of date. If this isn't something you want to do I'm fine with manually depending on jackson in my build scripts.

**Comment by modmuss50** [comment]
Im going to close this, this is not a good fix to the issue you are describing. Either way I updated all in the libs fo 0.11

**Pull request closed without merging**
