### PR TITLE
[WIP] Gradle 7

### PR DESCRIPTION
**Pull request by modmuss50**
This PR updates loom to build against gradle 7 and groovy 3.

### CODE REVIEW

**Comment by modmuss50** [comment]
Going to put this on hold a bit, stuff seems a little rough around the edges, no docker images and the testing framework doesnt seem to be too happy currently.

**Review by liach — APPROVED** [review]
Nice

**Comment by modmuss50** [comment]
I have resolved most of the issues, I forked the docker images and started to build 7.0-rc2 + jdk16 images, there were a few test failuires.

Just the kotlin test is failing on JDK16 now.

**Comment by modmuss50** [comment]
Looks to be a kotlin issue: https://youtrack.jetbrains.com/issue/KT-45566 Seems to be fixed in 1.5

**Comment by liach** [comment]
Fyi yarn builds quite well on gradle 7 rc 2 on my side, just fyi. It only sends some warning on implicit task dependency due to shared temp folders. It only warns like this for some tasks:
```
Execution optimizations have been disabled for task ':javadocJar' to ensure correctness due to the following reasons:
  - Gradle detected a problem with the following location: 'C:\code\yarn\build\docs\javadoc'. Reason: Task ':javadocJar' uses this output of task ':copyCopyOnClickScript' without declaring an explicit or implicit dependency. This can lead to incorrect results being produced, depending on what order the tasks are executed. Please refer to https://docs.gradle.org/7.0-rc-2/userguide/validation_problems.html#implicit_dependency for more details about this problem.
```
Link: https://docs.gradle.org/7.0-rc-2/userguide/validation_problems.html#implicit_dependency

**Comment by modmuss50** [comment]
That’s good to know, ideally actions should be running with warm mode fail from now on. Will give us advanced warning of breakages.

**Comment by modmuss50** [comment]
Going to pull this into a WIP branch where I can PR against it easily.

**Pull request merged**
