### PR TITLE
Split out and organize some constants

### PR DESCRIPTION
**Pull request by i509VCB**
This pull request reorganizes parts of the constants class into categories based on sub-classes and moves some constants into this class

### CODE REVIEW

**Review by zml2008 — APPROVED** [review]
This is a good change to help get the codebase organized. I'd like to see this in sooner rather than later so that the structure is there, even if it doesn't hit every constant just yet.

Once this PR provides the structure, it'll be easier for any PRs in flight to add to the constants without as many merge conflicts.

**Comment by i509VCB** [comment]
Ah yes conflicts again

**Review by modmuss50 — APPROVED** [review]
Looks good, fix conflicts and then this can go in.

**Comment by i509VCB** [comment]
conflicts should be fixed

**Pull request merged**
