### PR TITLE
CRF linenumbers take 2

### PR DESCRIPTION
**Pull request by modmuss50**
Something is still wrong, not sure what though...

Inner classes seem to be handled wrong, might be the cause of this?

### CODE REVIEW

**Comment by liach** [comment]
I remember that inner classes are dumped with dumpers with a custom type usage information. A bad overriding for one of those methods in cfr's code may be the problem. Also consider using fabric cfr, which supports adding javadoc to the decompiled code and naming lambdas.

**Comment by modmuss50** [comment]
Yeah, we need to update fabric's cfr to include the linenumber changes first, getting it in here is easy enough but not worth doing if this issue cannot be fixed.

**Comment by liach** [comment]
hmm, our cfr is up to date to at least jan 21. line number was aug 20 in upstream.

**Comment by modmuss50** [comment]
Oh, so it is 👍

**Comment by modmuss50** [comment]
Got a take 3 in the works, will open a new PR.

**Pull request closed without merging**
