### PR TITLE
Only quote program arguments if they actually contain spaces

### PR DESCRIPTION
**Pull request by shartte**
Fixes arguments like "--username" not being recognized by MC due to unnecessary quoting.

### CODE REVIEW

**Comment by shartte** [comment]
@modmuss50 Tests are failing with UnknownHostException which I doubt is related to this change. Can you please re-run the checks?

**Comment by modmuss50** [comment]
Rerunning, I do want to test this with the range of IDEs before merging it. I think this is fine tho.

**Review by modmuss50 — APPROVED** [review]

**Review by modmuss50 — CHANGES_REQUESTED** [review]
The RunConfigUnitTest are failing.

**Comment by modmuss50** [comment]
Fixed tests and pushed into the 0.11 branch. Thanks.

**Pull request closed without merging**
