### PR TITLE
IntelliJ Code-Style Config

### PR DESCRIPTION
**Pull request by shartte**
I can see that you attempted to add this to .editorconfig. I don't know if this works for anyone? If it does, it certainly does absolutly nothing for me and routline fails to apply the correct order.

The files in this PR however, will be picked up automatically and applied correctly.

### CODE REVIEW

**Comment by modmuss50** [comment]
The editorconfig file works great for me, im not sure if its plugin I added but I think it comes enabled by default with idea.

**Comment by haykam821** [comment]
I use [this extension](https://github.com/editorconfig/editorconfig-vscode) for editor config support on Visual Studio Code. As far as I'm aware, there's no way to use IntelliJ code style configurations on Visual Studio Code.

**Comment by shartte** [comment]
It even says this in the editor footer, and _STILL_ uses the incorrect import order, without anything else applied project-local:

grafik

After actually copying the files in this PR over from my local fabric-api project, it finally _does_ work.

p.s.: I am on the latest IntelliJ version, but this has never worked right for me, even months ago.

**Comment by Juuxel** [comment]
Also for import ordering, I've noticed that idea likes to put them in its default order when importing, and then I have to force the .editorconfig ordering with ctrl+alt+O / `optimise imports`

**Comment by modmuss50** [comment]
Closing this as the editorconfig and spotless settings are working well, we dont use this on any other projects. Thanks.

**Pull request closed without merging**
