### PR TITLE
Fix being unable to refresh gradle while the game is running

### PR DESCRIPTION
**Pull request by natanfudge**

### CODE REVIEW

**Comment by modmuss50** [comment]
Id rarther crash here, and print out a warning to ensure the game is closed.

**Comment by natanfudge** [comment]
Why crash? Refreshing should be able to work just fine.

**Comment by modmuss50** [comment]
it could fail silently in other cases, loom shouldnt be used when the game is open, there is no reason for it to.

**Comment by natanfudge** [comment]
I want to genSources while the game is running. Loom always allowed refreshing when the game is running, it just stopped working when the natives were added.

**Comment by immibis** [comment]
I think it would be better to not extract the file if it hasn't changed.

**Comment by modmuss50** [comment]
Closing this as its not the fix. the fix is to not exact the natives each run.

**Pull request closed without merging**
