### PR TITLE
Match Mercury sourceCompatibility with Gradle

### PR DESCRIPTION
**Pull request by jamierocks**

### CODE REVIEW

**Comment by modmuss50** [comment]
Looks good, just needs checkstyle fixing.

**Comment by jamierocks** [comment]
> Looks good, just needs checkstyle fixing.

How would I go about doing that?

**Comment by modmuss50** [comment]
either use an IDE plugin, or run the `checkstyle` task to see whats wrong.

**Comment by jamierocks** [comment]
That is hiddeous, but there you are :)

**Review by liach — APPROVED** [review]
Guess checkstyle wants `? branch1` `: branch2` style stuff

**Comment by liach** [comment]
Also is it possible to bump mercury so that we have javadoc remapping?

**Review by modmuss50 — APPROVED** [review]

**Pull request merged**
