### PR TITLE
Gradle 8.4, Kotlin 1.9.10

### PR DESCRIPTION
**Pull request by JT122406**
Updates to Gradle 8.4 and Kotlin 1.9.10 which is the version included in 8.4

### CODE REVIEW

**Comment by modmuss50** [comment]
Thanks for the PR, is there a need for this? Generally we only bump the gradle version when required. In 1.3 this was due to the kotlin metadata library requiring a newer Kotlin version.

When bumping the gradle version the min version should also be bumped in the bootstrap.

**Comment by JT122406** [comment]
Seemed like y'all were bumping gradle with almost every new loom version

**Comment by modmuss50** [comment]
> Seemed like y'all were bumping gradle with almost every new loom version

Maybe we should make that rule? Usually there is a good reason to (either new features, or a forced update due to another dep).

**Comment by JT122406** [comment]
Yeah lol

**Comment by JT122406** [comment]
but you see what I mean

**Pull request closed without merging**
