### PR TITLE
Fix another broken library pom

### PR DESCRIPTION
**Pull request by thecatcore**

### CODE REVIEW

**Comment by modmuss50** [comment]
What MC version is this from? Do you mind adding it to the approiate test in: https://github.com/FabricMC/fabric-loom/blob/dev/0.12/src/test/groovy/net/fabricmc/loom/test/integration/LegacyProjectTest.groovy

**Comment by thecatcore** [comment]
Done

**Comment by thecatcore** [comment]
I don't know why windows decompile test is failing.

**Review by PseudoDistant — APPROVED** [review]
Hi

**Comment by modmuss50** [comment]
> I don't know why windows decompile test is failing.

Dont worry about that test, its very flakey.

**Review by modmuss50 — APPROVED** [review]

**Pull request merged**
