### PR TITLE
Pretty-print the modified fabric.mod.json in ModResolver

### PR DESCRIPTION
**Pull request by AlexIIL**
...Because this one didn't used to, and it's a lot nicer to read than if it's on a single line.

If there's any reason why this *isn't* wanted then I'd quite like to add a comment here, as it's probably going to annoy me again in the future :p

### CODE REVIEW

**Comment by asiekierka** [comment]
Non-pretty-printed JSONs are probably slightly smaller compressed and slightly faster to read, though the difference probably doesn't even hit the milliseconds.

**Comment by liach** [comment]
do pretty print please. using gson already made things slow, we don't mind if it gets slower

**Comment by modmuss50** [comment]
I see no issue in this, its loom, its not like every milisecond counts.

**Comment by liach** [comment]
well nowadays people don't care about such tiny size differences and the mod json is load only once on game launch.

**Comment by AlexIIL** [comment]
This only affects the fabric.mod.json that loom transforms *after* downloading from maven, but before it's opened by the dev - released jars have always been pretty-printed AFAIK.

**Pull request merged**
