### PR TITLE
add nogui to server program arguments

### LINKED ISSUE #276: pass the "nogui" argument to the server run configuration by default
Pass the "nogui" argument to the server run configuration by default and allow it to be removed. The GUI is unnecessary and troublesome, and the default run script on [minecraft.net](https://www.minecraft.net/en-us/download/server) includes it. IDEs should have built-in consoles so they do not need an additional window for a server.

### PR DESCRIPTION
**Pull request by nnym**
close #276

### CODE REVIEW

**Comment by nnym** [comment]
Why did the 4.9 and 4.10.2 tests fail? 🤔

**Comment by CoolMineman** [comment]
sometimes the tests just randomly fail just push empty commits until it works

**Review by modmuss50 — APPROVED** [review]

**Comment by spaceclouds42** [comment]
@user11681 On your issue (#276), you mention that it should be optional. I am having trouble making a run task that runs with the gui. I tried the following but it didn't actually change the `programArgs` to be empty, and when I ran `./gradlew runGuiServer` it ran no different than `./gradlew runServer`. How would I remove the `nogui` arg?
```groovy
loom {
    runs {
         guiServer {
             server()
             ideConfigGenerated project.rootProject == project
             name = "Gui Server"
             source sourceSets.main
             programArgs ""
         }
    }
}
```

**Comment by modmuss50** [comment]
```
loom {
    runs {
         guiServer {
             server()
             ideConfigGenerated project.rootProject == project
             name = "Gui Server"
             source sourceSets.main
             serverWithGui()
         }
    }
}
```

Should do it

**Comment by spaceclouds42** [comment]
Thank you, that worked!

**Pull request merged**
