### PR TITLE
fix: make JarNester deterministic

### PR DESCRIPTION
**Pull request by ashhhleyyy**
Sorts the list of jars to nest before adding them to fabric.mod.json to ensure the ordering is deterministic.

### CODE REVIEW

**Comment by solonovamax** [comment]
~~sorting it only if the `isReproducibleFileOrder` may be a desired solution as it avoides sorting when determinism isn't desired~~
from the fabric discord:
> Everything should be reproducible by default, I think this one would be a regression

also, the sort order *can* be different on windows vs unix, as-per the javadocs for `File.compareTo`:
> Compares two abstract pathnames lexicographically. The ordering defined by this method depends upon the underlying system. On UNIX systems, alphabetic case is significant in comparing pathnames; on Microsoft Windows systems it is not.

it may be desireable to `.toLowerCase()` the pathnames first before sorting (also possibly to ensure the input files are absolute and/or only sort using the base file name?)

**Comment by ashhhleyyy** [comment]
I think just using the filename would be okay as using the absolute path makes it dependent on the build environment, and only the filename makes it into the jar. I don't think it's a good idea to lower-case them first, since then two files with different cases will get sorted the same, and the ordering between the two becomes platform dependent again

**Comment by solonovamax** [comment]
> I think just using the filename would be okay as using the absolute path makes it dependent on the build environment, and only the filename makes it into the jar. I don't think it's a good idea to lower-case them first, since then two files with different cases will get sorted the same, and the ordering between the two becomes platform dependent again

if you don't want to lowercase them, then make sure to sort using the `String` representation of the file/filename rather than the `File` representation

**Comment by ashhhleyyy** [comment]
yeah, i meant to push the change that went along with that but forgor, will push when i get home

**Review by solonovamax — APPROVED** [review]
LGTM

**Review by LambdAurora — APPROVED** [review]

**Review by modmuss50 — APPROVED** [review]

**Pull request merged**
