### PR TITLE
FIx Annotation Processing when scalac defers to javac

### PR DESCRIPTION
**Pull request by Khitiara**
This allows java mixins in the scala source directory, allowing java mixin code to call methods in scala classes without dirty hacks. Tested on https://github.com/robotbrain/luminiferous-uplands/tree/loom-scalac-fix

### CODE REVIEW

**Review by modmuss50 — CHANGES_REQUESTED** [review]
Don’t reformat the class, it’s busily impossible to see what has been changed. 

Thanks

**Comment by Khitiara** [comment]
Unformatted the class, so fixed

**Comment by Khitiara** [comment]
Also noting that this PR does **NOT** allow mixins to be written in scala, merely for mixins written in java to properly coexist with scala classes

**Review by modmuss50 — APPROVED** [review]
Seems like a reasonable fix, I assume this has been tested on scala and none scala projects?

**Comment by Khitiara** [comment]
Yup, has been tested on both

**Pull request merged**
