### PR TITLE
Side stripping Jar processor

### PR DESCRIPTION
**Pull request by ramidzkh**
Allows users to remove client or server only members from their local development Minecraft Jar

### CODE REVIEW

**Comment by ramidzkh** [comment]
Usage:
```groovy
import net.fabricmc.loom.processors.side.SideStripperJarProcessor

minecraft {
	addJarProcessor(SideStripperJarProcessor.SERVER) // For keeping only common or server-only members
        // addJarProcessor(SideStripperJarProcessor.CLIENT) For keeping only common or client-only members
}
```

**Comment by NickAcPT** [comment]
Just wondering, does this affect the Mixins configuration at all? If it doesn't, is it needed?

**Comment by ramidzkh** [comment]
Nope, just removes client/server only classes so you don't need to deal with it. My purpose is so that I can fully remove client only members from [CannedTater](https://github.com/FukkitMC/CannedTater) and make it actually launch without anonymous classes ruining it for everyone. Also, my reason for making this a feature PR is that more people can use it (lets say you want to develop a server-side only mod), and that implementing a processor like this in your own buildscript would be painful

**Review by hYdos — APPROVED** [review]

**Review by Ueaj-Kerman — APPROVED** [review]

**Comment by modmuss50** [comment]
Going to close this PR, it should now be trivial to do properly using the new changes I added to support splitting the jars.

**Pull request closed without merging**
