### PR TITLE
Change zip entry ordering to place manifest first

### PR DESCRIPTION
**Pull request by lukebemish**
This should solve #885; I've tested it with the reproduction case I provided for that issue, and it correctly reorders the zip entries.

### CODE REVIEW

**Comment by lukebemish** [comment]
Marking as a draft as it looks like there's other files this will need to handle too: https://docs.oracle.com/en/java/javase/20/docs/specs/jar/jar.html#signed-jar-file

**Comment by lukebemish** [comment]
Alright, that implementation should match what java expects for jars. For posterity's sake, the use of a `JarInputStream` (which isn't great to use, but is still used quite often) assumes that:
> * The Manifest is the first entry in the stream (or the second entry if the first entry in the stream is META-INF/ and the second entry is META-INF/MANIFEST.MF).
> * All signature-related entries immediately follow the Manifest

(from https://docs.oracle.com/en/java/javase/20/docs/api/java.base/java/util/jar/JarInputStream.html)

**Comment by modmuss50** [comment]
I think the https://github.com/FabricMC/fabric-loom/blob/dev/1.2/src/test/groovy/net/fabricmc/loom/test/integration/ReproducibleBuildTest.groovy tests are going to need updating. Might be kinda nice to read the jars with JarInputStream as well.

**Comment by lukebemish** [comment]
Hmm, wait, that doesn't seem to be working quite as expected... yeah, let me try and see if I can get all the hashes correct

**Comment by lukebemish** [comment]
Alright, that should be correct. At any rate, the test runs locally, and I even switched the line endings around to get both source possibilities..

**Comment by modmuss50** [comment]
The tests arent working still. The mod jar seems to now be `174c9b52f4bc6d489548d11b42e853cf` I reccomend getting the hash from the github actions build.

**Comment by lukebemish** [comment]
> The tests arent working still. The mod jar seems to now be `174c9b52f4bc6d489548d11b42e853cf` I reccomend getting the hash from the github actions build.

That is... worrying, then, since that's not the hash when I run it locally (and, well, it should be if we're going for reproducible builds)

**Comment by lukebemish** [comment]
Alright, I've changed the hashes - I'm still worried about why it differs locally vs on the test here, but honestly I have no clue. The sources jar hashes may be out of date - I don't have an easy way to get those now

**Comment by lukebemish** [comment]
Alright, the source hashes should be updated. I'm still not sure why it didn't match locally, but it seems alright here at least.

**Review by modmuss50 — APPROVED** [review]

**Pull request merged**
