### PR TITLE
Add loom development dependencies to test runtime classpath

### LINKED ISSUE #385: Minecraft can't be run using test classpath
The issue is that `loomDevelopmentDependencies` is added to `runtimeClasspath`, but not to `testRuntimeClasspath`, causing `ClassNotFoundException: net.fabricmc.devlaunchinjector.Main` when trying to run Minecraft from Intellij with the test module.

A workaround I found is adding this to build.gradle
```gradle
configurations {
    testRuntimeClasspath.extendsFrom loomDevelopmentDependencies
}
```
This affects 0.6 - not sure about other versions

### PR DESCRIPTION
**Pull request by IotaBread**
Resolves #385

### CODE REVIEW

**Comment by modmuss50** [comment]
This seems fine, I dont think this should be needed across all source sets?

**Comment by modmuss50** [comment]
shit, that should have not go into 0.6

**Comment by modmuss50** [comment]
This needs to go into 0.7 as its technically a breaking change, I have cancled the builds for 0.6 and reverted it.

**Comment by IotaBread** [comment]
Opened #389 targeting 0.7

**Pull request merged**
